<a href="https://colab.research.google.com/github/praneeth-9589417/2024-stat-ml-assignments/blob/main/SML_LAB_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

QUESTION : 1

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
data = {
    'X1': [10, 5, 15, 2, 12, 8, 14, 3, 11, 6],
    'X2': [90, 60, 95, 30, 85, 75, 92, 50, 88, 65],
    'X3': [85, 70, 90, 50, 88, 65, 93, 55, 80, 60],
    'X4': [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    'X5': [100, 80, 100, 40, 90, 70, 95, 60, 85, 75],
    'Pass/Fail': [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
}

In [ ]:
df = pd.DataFrame(data)

X = df.drop('Pass/Fail', axis=1)
y = df['Pass/Fail']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
classification_report_result = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


In [ ]:
print("Logistic Regression Model Results:")
print(f"Accuracy: {accuracy * 100:.2f}%")
print("\nClassification Report:\n", classification_report_result)
for i in range(len(y_test)):
    print(f"Actual: {y_test.iloc[i]}, Predicted: {y_pred[i]}")
    print("-" * 30)
    print()
print("\nModel Coefficients:")
for feature, coef in zip(["X1", "X2", "X3", "X4", "X5"], model.coef_[0]):
    print(f"{feature}: {coef:.4f}")

Logistic Regression Model Results:
Accuracy: 100.00%

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

Actual: 1, Predicted: 1
------------------------------

Actual: 0, Predicted: 0
------------------------------


Model Coefficients:
X1: 0.0379
X2: 0.1176
X3: 0.2115
X4: 0.0088
X5: 0.1849


QUESTION :2

In [ ]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.linear_model import LogisticRegression

In [ ]:
data2 = pd.read_csv('/content/diabetes_data_upload.csv')
data2.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

*Calling out the Variables and declaring the target-variable.*

In [ ]:
x0 = 1
x1 = data2['Age']
x2 = data2['Gender']
x3 = data2['Polyuria']
x4 = data2['Polydipsia']
x5 = data2['sudden weight loss']
x6 = data2['weakness']
x7 = data2['Polyphagia']
x8 = data2['Genital thrush']
x9 = data2['visual blurring']
x10 = data2['Itching']
x11 = data2['Irritability']
x12 = data2['delayed healing']
x13 = data2['partial paresis']
x14 = data2['muscle stiffness']
x15 = data2['Alopecia']
x16 = data2['Obesity']

#TARGET VARIABLE.
y = data2['class']

*Mapping the variables and target-variable.*

In [ ]:

x2 = x2.map({'Male': 1, 'Female': 0})
x3 = x3.map({'Yes': 1, 'No': 0})
x4 = x4.map({'Yes': 1, 'No': 0})
x5 = x5.map({'Yes': 1, 'No': 0})
x6 = x6.map({'Yes': 1, 'No': 0})
x7 = x7.map({'Yes': 1, 'No': 0})
x8 = x8.map({'Yes': 1, 'No': 0})
x9 = x9.map({'Yes': 1, 'No': 0})
x10 = x10.map({'Yes': 1, 'No': 0})
x11 = x11.map({'Yes': 1, 'No': 0})
x12 = x12.map({'Yes': 1, 'No': 0})
x13 = x13.map({'Yes': 1, 'No': 0})
x14 = x14.map({'Yes': 1, 'No': 0})
x15 = x15.map({'Yes': 1, 'No': 0})
x16 = x16.map({'Yes': 1, 'No': 0})

y = y.map({'Positive': 1, 'Negative': 0})

In [ ]:
X = np.array(list(zip(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16)))
Y = np.array(y)

*Training and Testing the data*

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
X_train

array([[27,  1,  0, ...,  0,  0,  0],
       [47,  1,  0, ...,  0,  0,  1],
       [66,  0,  1, ...,  1,  0,  0],
       ...,
       [70,  1,  0, ...,  0,  1,  0],
       [48,  1,  1, ...,  0,  0,  0],
       [64,  1,  0, ...,  0,  0,  0]])

In [ ]:
X_test

array([[67,  1,  0, ...,  1,  1,  1],
       [47,  1,  1, ...,  1,  0,  0],
       [43,  0,  1, ...,  1,  0,  1],
       ...,
       [46,  0,  1, ...,  1,  0,  0],
       [48,  0,  1, ...,  1,  1,  1],
       [33,  1,  0, ...,  0,  0,  0]])

In [ ]:
Y_train

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,

In [ ]:
Y_test

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1])

*Initializing the Logistic-Regression Model*

In [ ]:
lo_r = LogisticRegression()

*Fitting the training value for X and Y*

In [ ]:
lo_r.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

*Predict using the trained model on the test data*

In [ ]:
yp = lo_r.predict(X_test)

*Calculate accuracy on the test dataset*

In [ ]:
corr_pred = 0
for i in range(len(Y_test)):
  if Y_test[i] == yp[i]:
    corr_pred += 1

accuracy = corr_pred / len(Y_test)*100
print(accuracy)

95.1923076923077
